- name: Setup New Machine
  hosts: newmachine
  become: true
  vars_prompt:
   - name: Hostname
     prompt: Enter new VM hostname
     private: false
   - name: NeedsTailscale
     prompt: Does this VM need Tailscale? (y/n)
     default: 'n'
     private: false
  tasks:
   - name: Update hostname
     ansible.builtin.lineinfile:
       path: /etc/hostname
       search_string: 'template-vm'
       line: '{{Hostname}}'
   - name: Update hosts file
     ansible.builtin.lineinfile:
       path: /etc/hosts
       search_string: '127.0.1.1'
       line: '127.0.1.1  {{Hostname}}'
   - name: Update apt cache
     apt: update_cache=yes force_apt_get=yes
   - name: Upgrade system
     apt: upgrade=dist force_apt_get=yes
   - name: Install qemu guest agent
     ansible.builtin.apt:
       name: qemu-guest-agent
   - name: Install Tailscale
     shell: curl -fsSL https://tailscale.com/install.sh | sh
     when: NeedsTailscale == 'y'
   - name: Shutdown host
     community.general.shutdown:
