- name: Update Ubuntu
  hosts: newmachine
  tasks:
   - name: Update apt cache
     become: true
     apt: update_cache=yes force_apt_get=yes
   - name: Upgrade system
     become: true
     apt: upgrade=dist force_apt_get=yes

